version: 2.1 # CircleCI version
workflows:
  build_and_deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: master
jobs:
  test:
    docker:
      - image: fkrull/multi-python
    steps:
      - checkout
      - run:
          name: Test
          command: 'tox'
  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip3 install -r requirements_dev.txt
      - run:
          name: build package for release
          command: |
            pip3 install twine
            python3 setup.py bdist_wheel
      - run:
          name: Deploy package to PyPi
          command: |
            . env/bin/activate
            twine upload dist/* -p ${PYPI_PASSWORD} -u  ${PYPI_USERNAME}
